[package]
name = "hash"
version = "0.1.0"
authors = ["Bottom-Labs <bottomlabs@163.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sha2 = "0.9.2"
digest = "0.9.0"
hex = "0.4.2"
tiny-keccak = "1.4"